select session_id,
       subsession_id,
       start_time,
       end_time,
       license_category,
       num_drivers,
       num_cautions,
       num_caution_laps,
       num_lead_changes,
       event_laps_complete,
       driver_changes,
       winner_group_id,
       winner_name,
       tupleElement(track, 1) as track_config,
       tupleElement(track, 3) as track_name,
       official_session,
       season_id,
       season_year,
       season_quarter,
       event_type,
       event_type_name,
       series_id,
       series_name,
       series_short_name,
       race_week_num,
       event_strength_of_field,
       event_average_lap,
       event_best_lap_time
from iracing.v_series
where subsession_id = %(subsession_id)s