version: '3.8'

services:
  web:
    build: .
    depends_on:
      - cache
    #env_file:
    #  - stack.env
    networks:
      - webnet
    ports:
      - "8000:8000"
    env:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    env_file:
      - .env

  cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel verbose
    volumes:
      - redis-data:/data
    networks:
      - webnet

volumes:
  redis-data:
    driver: local

networks:
  apinet:
    driver: bridge